JupiterOne/docs-old

guides/j1-queries-for-aws-config.md, guides/tutorial-j1ql.md, queries/common-qq-apps-processes.md, queries/common-qq-aws-permissions.md, queries/common-qq-dev.md, queries/common-qq-idp.md, queries/common-qq-inventory-config.md, queries/common-qq-network.md, queries/common-qq-risks.md, queries/common-qq-training.md
Line breaks in paragraphs of italics will not be picked up by a lot of markdown parsers. We cannot put line breaks in italics (_ or * blocks).
=> remove line breaks italics

assets/icons/pagerduty.svg
=> Add PagerDuty icon

docs/bulk-upload.md, docs/jupiterone-api.md, docs/schemas/bulk-upload.md
Docs for the bulk upload of assets/relationships feature
=> Adding bulk upload docs

docs/data-model/development.md, docs/data-model/people.md, zendesk/config.yaml, zendesk/links.json
the links were somehow messed up
=> fix broken image links

docs/integrations/google/jupiter-integration-google.md
Google has changed their admin console, we need some updates so folks don't get lost. Note there are two PRs (monorepo and docs) Monorepo is more up to date, here is monorepo PR: https://github.com/JupiterOne/jupiter-web-monorepo/pull/131
=> Update Google integration doc with new Admin UI info

docs/integrations/google/jupiter-integration-google.md
docs were out of sync with /graph-google/docs
=> Update Google integration docs from source

docs/schemas/alert-rule.md
Moving the JSON Slack rule example here and adding some more details for clarity and some key words for search.
=> Add JSON Slack rule example here from Slack docs

docs/integrations/google-cloud/index.md
GCP docs have had a lot of new changes recently - only ~5 new lines needed at the source today (graph-google-cloud), but ~100 lines need to be added here
=> Update google cloud docs with roles/iam.roleViewer

docs/jupiterone-api.md
This also documents the `deferredResponse` option as well.
=> AB#1930 - document j1ql cursors

docs/integrations/google/jupiter-integration-google.md
@a-u-h-g If the list_token_error section looks good I'll copy that over to the graph-google repo as well.
=> Match the docs and explain list_token_error

docs/integrations/azure/graph-azure.md
=> AB#3052 update azure docs from latest graph-azure

docs/integrations/google-cloud/index.md
The docs repo integration for google cloud was out of old and out of sync. New changes.
=> Update to sync with graph-google-cloud

docs/jupiterone-api.md
Adding Alert Intervals per internal convo, and also changed headings to H2 so the documentation page will automatically create anchors for deeplinks to them. (necessary for such a long doc)
=> Update API Docs w/ alert intervals + link headings

docs/integrations/microsoft365/index.md
adding docs from integration repo
=> Add Microsoft 365 doc from integration repo

docs/jupiterone-api.md
There will be a separate PR for bulk delete. Are there other Request Flags/Request Body Properties I should call out? Thanks!
=> Ab#2343 bulk update api

docs/integrations/rapid7/index.md
made some changes at the source docs and replicating here - remove duplicate header + add auth info
=> Update rapid 7 docs

rcas/20210309-cognito-outage.md
Creating a public docs folder for our RCAs to share with customers, including the RCA from 2021-03-09, removed internal links/references
=> Add rca 20210309

docs/data-model/org-grc.md
first draft of GRC data model narrative
=> first draft of GRC data model narrative

docs/jupiterone-data-security.md
Not sure if/how we want to call out access to callisto.
=> Update support access info

docs/data-model/mappings-global.md, docs/data-model/mappings-integrations.md
Generated using https://bitbucket.org/jupiterone/jupiter-mapper/src/master/src/docs/.
@erkangz these will need publishing.
=> Update mappings docs

docs/integrations/google/jupiter-integration-google.md
=> Update google documentation from source

src/zendesk/config.yaml
=> publish recent api docs changes

docs/integrations/google/index.md
=> deleted line

docs/jupiterone-api.md
Added updateIamGroup and createIAMGroup + formatting
=> added group mamangement docs and did a little cleaning

docs/integrations/microsoft-365/index.md
correct image references for zendesk publishing
=> fix m365 pics

docs/jupiterone-api.md
- updated variable types in `updateIamGroup` and `createIamGroup` to `[JSON!]`. 
- labeled sample requests
=> updated variable type to [JSON]

docs/integrations/azure/index.md
Added words for clarity, and pulled from graph-azure documentation
=> Sol 1328 azure docs update walkthrough

docs/integrations/azure/index.md, docs/integrations/cisco-amp/index.md, docs/integrations/google-cloud/index.md, docs/integrations/google/index.md, docs/integrations/heroku/index.md, docs/integrations/npm/index.md, docs/integrations/okta/index.md, docs/integrations/snowflake/index.md, docs/integrations/tenable-cloud/index.md, docs/integrations/trend-micro/index.md, src/zendesk/config.yaml
=> Publish branch 072621

docs/integrations/azure/index.md, src/zendesk/config.yaml, src/zendesk/links.json
=> Publish azure troubleshooting

src/zendesk/config.yaml
=> publish api docs

docs/jupiterone-api.md
Thanks for catching this @austinkelleher !
=> Fix type for example query in api docs

docs/integrations/google-cloud/index.md, docs/integrations/knowbe4/index.md, docs/integrations/onelogin/index.md, docs/integrations/slack/index.md, src/zendesk/config.yaml
=> Publish int docs 20210803

release-notes/2019-18.md, release-notes/2019-20.md, release-notes/2019-21.md
Please approve and merge when able.
=> change links in release notes, and removed openshift

src/zendesk/config.yaml
=> update docs to support remove openshift references

docs/jupiterone-query-language.md
Adding preliminary documentation to usage of the Scalar Functions and the first implementation of CONCAT.
I tried to match this section to the ones around it, though if you'd like to see more detail or changes to the wording I can make any changes needed 👍
=> Adding documentation references to CONCAT

src/zendesk/config.yaml, src/zendesk/links.json
=> publish sso updates

docs/integrations/aws/index.md, src/zendesk/config.yaml
=> Update aws docs 20210806

src/zendesk/config.yaml, src/zendesk/publish.js
=> Update docs and main branch assets

src/zendesk/config.yaml
=> publish updates to docs

release-notes/2021-77.md
moved from Aug 24th to Aug 31st to provide time to notify customers.
=> Update to target release date of De Morgan's law change

src/zendesk/config.yaml
=> update api docs and release notes 77

src/zendesk/config.yaml
=> publish J1QL, alert rule, and API docs

src/zendesk/config.yaml
=> publish updates for de morgan's law and isSecret

release-notes/2021-79.md
Capitalization consistency changes and active voice changes.
=> RNs - Minor Edits

guides/manage-alerts.md
@cat9563 saw some spelling errors in our alerts doc, and I wanted to show her how to update them as well.
=> spelling in alerts doc

docs/integrations/auth0/index.md, docs/integrations/crowdstrike/index.md, docs/integrations/google-cloud/index.md, docs/integrations/google/index.md, docs/integrations/jamf/index.md, docs/integrations/jira/index.md, docs/integrations/onelogin/index.md, docs/integrations/rapid7/index.md, docs/integrations/snyk/index.md, docs/integrations/tenable-cloud/index.md, src/zendesk/config.yaml
=> Publish 20210913

release-notes/2021-80.md
First draft. Waiting for more input on new features and bug fixes.
=> 2021 80 Release Notes

docs/jupiterone-api.md, src/zendesk/config.yaml
=> Publish 20211101

docs/jupiterone-query-language.md
=> Fixed broken link

docs/integrations/azure/index.md, docs/integrations/cbdefense/index.md, docs/integrations/feroot/index.md, docs/integrations/google-cloud/index.md, docs/integrations/jamf/index.md, docs/integrations/jumpcloud/index.md, docs/integrations/knowbe4/index.md, docs/integrations/microsoft-365/index.md, docs/integrations/nowsecure/index.md, docs/integrations/sentinelone/index.md, docs/integrations/slack/index.md
Not urgent. Just ran the script to pull some changes.
=> Run yarn build:docs:integrations

src/zendesk/config.yaml
=> publish updates 2021-11-14

release-notes/2021-84.md
First draft. Waiting on more input.
=> 2021-84 Release Notes

docs/integrations/crowdstrike/index.md, docs/integrations/google/index.md, docs/integrations/jira/index.md, src/zendesk/config.yaml
=> Publish 20211130

docs/integrations/splunk/index.md
Doc page for the Splunk integration.  Describes features and how to configure it.
=> index.md file for Splunk integration

docs/jupiterone-query-language.md, docs/schemas/alert-rule.md, guides/asset-inventory-filters.md, guides/insights-dashboards.md
Fix bold syntax
Update alert query polling intervals.
=> DOC-36 and DOC-44

src/zendesk/config.yaml
add splunk screenshots and other docs improvements
please merge after approval
=> publish docs updates for PRs 431+

docs/integrations/jira/index.md, docs/integrations/okta/index.md, src/zendesk/config.yaml, src/zendesk/links.json
=> Publish 20220105

docs/integrations/jira/index.md, docs/integrations/okta/index.md, src/zendesk/config.yaml
=> Publish 20220112

docs/integrations/servicenow/index.md, src/zendesk/config.yaml, src/zendesk/links.json
=> Sync servicenow docs 20220113

docs/integrations/bamboohr/index.md, docs/integrations/gitlab/index.md, src/zendesk/config.yaml
=> publish int docs and release notes updates - 20220127

src/zendesk/config.yaml
=> publish docs updates for compliance

src/zendesk/config.yaml
=> publish updated compliance gap matrix

release-notes/2022-FEB-21.md
- The Graph Viewer has a Load All button, allowing you to load all data from a query at one time. 
- Compliance now provides an evaluation status of linked questions as evidence in a framework.
- Compliance controls display their statuses in relation to the gap analysis.
- Questions linked as evidence to a framework in Compliance are now editable.
- A Compliance Gap rule is now available in Alerts. We will proactively add this rule to all accounts so that when a new gap is identified in your selected compliance frameworks, an alert is triggered. You can then customize your notification preferences for this alert.
- The Feature Request form has been updated for a better user experience.
- Released a new integration for Aqua Security
The following entities are created:
| Resources | Entity …
=> JupiterOne 23 February 2022 Release
